# Generated by Django 4.1.3 on 2023-02-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
